// Uses the Kotlin bindings generated by kextract from Shape.h (ObjC comprehensive example).
// Exercises: NS_OPTIONS bitflags, NS_ENUM, @protocol, @interface inheritance, category.
// Run ./run.sh to generate, compile and execute.
// Wildcard import so that category extension functions (e.g. Shape.perimeter())
// defined at package level in the generated binding are in scope.
import org.example.shapes.*

fun main() {
    // ── NS_OPTIONS: bitflags ──────────────────────────────────────────────────
    val filled   = ShapeOptions.ShapeOptionFilled    // rawValue = 1
    val bordered = ShapeOptions.ShapeOptionBordered  // rawValue = 2
    val combined = filled + bordered                  // rawValue = 3

    println("bitflags: combined=${combined.rawValue}")
    println("has-shadow: ${ShapeOptions.ShapeOptionShadow in combined}")

    // ── NS_ENUM: discriminant ──────────────────────────────────────────────────
    println("enum: kind=${ShapeKind.ShapeKindRectangle.value}")
    println("enum: fromValue=${ShapeKind.fromValue(0L)}")

    // ── ObjC base class: factory + methods ────────────────────────────────────
    // kextract maps the selector "shapeWithWidth:height:" → fun shapeWithWidth_height(w, h)
    val shapePtr = Shape.shapeWithWidth_height(5.0, 3.0)
    val shape    = Shape(shapePtr)

    println("area: ${shape.area()}")
    // NSString convenience overload generated by kextract: describeAsString()
    println("describe: ${shape.describeAsString()}")

    // ── Category (Shape+Geometry): perimeter extension function ───────────────
    println("perimeter: ${shape.perimeter()}")

    // ── ObjC inheritance: Rectangle extends Shape ─────────────────────────────
    // kextract maps "rectWithWidth:height:" → fun rectWithWidth_height(w, h)
    val rectPtr = Rectangle.rectWithWidth_height(4.0, 6.0)
    val rect    = Rectangle(rectPtr)

    // area() is inherited from Shape (not redeclared on Rectangle)
    println("rect-area: ${rect.area()}")
    // draw() is Rectangle's own Drawable implementation
    println("draw: ${ObjCRuntime.toJavaString(rect.draw())}")
    // perimeter() category extension also applies to the subtype
    println("rect-perimeter: ${rect.perimeter()}")
}
