// Uses the Kotlin bindings generated by kextract from Greeter.h (ObjC mode).
// Run ./run.sh to generate, compile and execute.
import org.example.greeter.Greeter
import org.example.greeter.ObjCRuntime
import java.lang.foreign.Arena

fun main() {
    Arena.ofConfined().use { arena ->
        // Greeter.create() — class method (+)
        val greeterPtr = Greeter.create()
        val greeter = Greeter(greeterPtr)

        // Build an NSString for the argument
        val namePtr = ObjCRuntime.newNSString(arena, "World")

        // greetWithName: — instance method (-)
        val resultPtr = greeter.greetWithName(namePtr)

        // Convert NSString result to Kotlin String
        println(ObjCRuntime.toJavaString(resultPtr))
    }
}
